### ISSUE TITLE
Currently mod won't run(for me)

### ISSUE THREAD

**Issue by CreepsPlays** [TheRexYo/Son-Of-War-Mod#2]
When selecting the mod normal "warnings" appear, but specifically an error occurs saying the Verdant Monument needs a tech or explicit cost. I'm not sure what's up or if this is an issue on my end, either way I thank you for your time.

**Comment by TheRexYo** [comment]
Sorry for the _extremely_ delayed response, I've been busy with college and stuff recently, so I haven't been able to work on 
the mod that much. When I can, I'll look into the error, but for now, I'll just say what I think is going on. I think it's because when I first added it, Verdant Monument was a more advanced building that took time to unlock (it was unlocked with the Theology tech, rather than being a starting building). However, I changed that recently, and made it an early-game replacement for the Monument building (which doesn't have a tech). Unfortunately, because I was used to it being an unlockable building as opposed to a starting one, I more or less forgot to give it a specific cost (since normally, each building's cost is specified by the tech that unlocks it, with only a few exceptions). So yeah, that's the gist of it. Thanks for taking time to write this!
